name: build

on:
  push:
  pull_request:
    branches: [ Lab2 ]
    paths:
    - 'Lab2/**.cs'
    - 'Lab2/**.csproj'

env:
  DOTNET_VERSION: '8.0' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore Lab2/Lab2-RPBDIS.sln

    - name: Build
      run: dotnet build Lab2/Lab2-RPBDIS.sln --configuration Release --no-restore

    - name: Log errors
      if: failure()
      run: |
        echo "Build failed. Checking logs..."
        cat Lab2/**/*.log
